name=DigitalFilter_dff
version=1.0.0
author=David Chirme Sisa <davidcs.ee.10@gmail.com>
maintainer=David Chirme Sisa <davidcs.ee.10@gmail.com>
sentence=Library for implementing discrete digital filters for Arduino and ESP32.
paragraph=Provides Moving Average and Exponentially Weighted Moving Average (EWMA) Low Pass filters for signal processing.
category=Signal Input/Output
url=https://github.com/bulb-light/DigitalFilter_dff
architectures=*
; dot_a_linkage=true